name: Feedback Report
description: File a feedback report
title: "M00-LAB00: QUICK_DESCRIPTION"
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this feedback report!
        
        > **Note**
        > Replace feedback name LAB00:QUICK_DESCRIPTION, for example "LAB01: My new feedback"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info 😉?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What should we change?
      description: What should we change?
      placeholder: Tell us your suggestion!
      value: SUGGESTION
    validations:
      required: true
  - type: textarea
    id: Screenshots
    attributes:
      label: Relevant screenshots
      description: Please copy and paste any relevant screenshots 📸
      value: paste here 😉 
  